In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

In [2]:
# Define directories for processed data and labels
processed_data_dir = r'C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data'
label_mapping_file = r'C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\labels.csv'  # Mapping of class labels to object names

In [3]:
# Load the label mapping (class names)
label_mapping_df = pd.read_csv(label_mapping_file)
class_names = label_mapping_df['Class'].values  # Class names (e.g., cat, dog, car, etc.)

In [8]:
# Check if 'Class' column exists and print the first few values
print("Class names from labels.csv file:")
print(label_mapping_df['Class'].head())  # Print the first few class names

Class names from labels.csv file:
0       cat
1       dog
2      fish
3    rabbit
4     horse
Name: Class, dtype: object


In [9]:
# Ensure class_names is a 1D array (e.g., ['cat', 'dog', 'fish', ...])
class_names = label_mapping_df['Class'].values  # Extract class names as a numpy array
print(f"Class names (total {len(class_names)} classes):", class_names)

Class names (total 19 classes): ['cat' 'dog' 'fish' 'rabbit' 'horse' 'elephant' 'car' 'truck' 'airplane'
 'bicycle' 'bus' 'house' 'tree' 'flower' 'computer' 'star' 'sun' 'moon'
 'smiley face']


In [6]:
def encode_labels(labels, class_names):
    """Convert labels to one-hot encoding."""
    # Ensure the labels are in a proper 1D format (list or numpy array)
    labels = np.array(labels).flatten()  # Ensure it's a 1D array

    # Initialize LabelEncoder
    label_encoder = LabelEncoder()
    label_encoder.fit(class_names)  # Fit the label encoder to the class names (no 'full_raw_' prefix)
    
    # Remove the 'full_raw_' prefix if it's part of the labels (fixing the KeyError)
    labels = [label.replace('full_raw_', '') for label in labels]
    
    # Convert labels to integers
    integer_labels = label_encoder.transform(labels)  # Convert labels to integers
    
    # One-Hot Encoding: Convert integer labels to one-hot encoding
    one_hot_labels = to_categorical(integer_labels, num_classes=len(class_names))  # One-hot encode
    return one_hot_labels, label_encoder.classes_

In [4]:
def process_labels_and_save(batch_index, label):
    """Load labels, apply one-hot encoding, and save them as .npy."""
    # Load the labels from the CSV file corresponding to the batch
    labels_file = os.path.join(processed_data_dir, f'full_raw_{label}_labels_{batch_index}.csv')
    labels_df = pd.read_csv(labels_file)
    
    # Extract the labels (ensure it's a 1D array of strings)
    labels = labels_df['label'].values.flatten()  # Flatten to ensure 1D array
    
    # Apply One-Hot Encoding
    num_classes = len(class_names)  # Total number of classes (19 in this case)
    one_hot_labels, _ = encode_labels(labels, class_names)  # Pass class_names to encode_labels
    
    # Save the one-hot encoded labels to a .npy file
    one_hot_labels_file = os.path.join(processed_data_dir, f'full_raw_{label}_one_hot_labels_{batch_index}.npy')
    np.save(one_hot_labels_file, one_hot_labels)  # Save as .npy for efficient loading later

    print(f"One-Hot Encoded Labels saved to: {one_hot_labels_file}")

In [7]:
# List of categories that had missing OHE files
missing_categories = ['bicycle', 'bus', 'computer', 'flower', 'horse', 'house', 'moon', 
                      'smiley face', 'sun', 'star', 'tree']

# Process all missing categories
for label in missing_categories:
    for batch_index in range(1, 11):  # Assuming 10 batches for each category
        process_labels_and_save(batch_index, label)


One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_bicycle_one_hot_labels_1.npy
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_bicycle_one_hot_labels_2.npy
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_bicycle_one_hot_labels_3.npy
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_bicycle_one_hot_labels_4.npy
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_bicycle_one_hot_labels_5.npy
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_bicycle_one_hot_labels_6.npy
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_bicycle_one_hot_label

In [12]:
# Process all label batches (from batch 1 to the total number of batches)
def process_all_batches():
    # List of labels (categories you are processing)
    labels = ['airplane', 'dog', 'cat', 'fish', 'truck', 'car', 'rabbit', 'elephant']  # Add all relevant categories

    # Loop through each label and batch
    for label in labels:
        for batch_index in range(1, 11):  # Assuming 10 batches (adjust as needed)
            print(f"Processing {label} Batch {batch_index}...")
            process_labels_and_save(batch_index, label)

In [13]:
# Run the process
process_all_batches()


Processing airplane Batch 1...
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_airplane_one_hot_labels_1.npy
Processing airplane Batch 2...
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_airplane_one_hot_labels_2.npy
Processing airplane Batch 3...
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_airplane_one_hot_labels_3.npy
Processing airplane Batch 4...
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_airplane_one_hot_labels_4.npy
Processing airplane Batch 5...
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\data\processed_data\full_raw_airplane_one_hot_labels_5.npy
Processing airplane Batch 6...
One-Hot Encoded Labels saved to: C:\Users\ACER\gitClones\QuickDrawGame\model_training\dat

In [16]:
# Load one of the saved one-hot encoded label files

one_hot_labels = np.load(r'C:\Users\ACER\gitClones\QuickDrawGame\model_training/data/processed_data/full_raw_airplane_one_hot_labels_1.npy')

# Check the shape of the one-hot encoded labels (should be [batch_size, num_classes])
print(one_hot_labels.shape)

# Print the first 5 labels to check if they are one-hot encoded correctly
print(one_hot_labels[:5])


(100, 19)
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
